### ISSUE TITLE
Squirrel Mount Viewer Crash

### ISSUE THREAD

**Issue by k0ttheawes0me1** [imathrowback/telarafly#15]
In the Mount Viewer if you try to view any of the squirrel mounts such as Opie it freezes.

**Comment by clowd81** [comment]
Do you have output logs? They should be generated in the same folder that you are running TelaraFly from.

**Comment by k0ttheawes0me1** [comment]
[output_log.txt](https://github.com/imathrowback/telarafly/files/1209638/output_log.txt)

**Comment by imathrowback** [comment]
I can't reproduce it, opie and squirrel mounts work fine for me when i run version 15, It might be fixed though in the next version, I've done some work on the model viewer to fix some other issues.

**Comment by imathrowback** [comment]
Closed due to no response and not reproducible
